### ISSUE TITLE
Is this deployed any blockchain network?

### ISSUE THREAD

**Issue by venustar1228** [c-spider/XSEED-Vesting#1]

**Comment by c-spider** [comment]
Yes. sure. It's going to be launched on Polygon Blockchain.

**Comment by c-spider** [comment]
yes. but recently deployed on testnet. Please check this link.
https://mumbai.polygonscan.com/address/0x483da03A27c05b641609AE6c7d040558B582db03

**Comment by venustar1228** [comment]
Enjoy your time.

**Comment by c-spider** [comment]
You too, man.
